### ISSUE TITLE
Issue: Can't define a custom location for the admin folder

### ISSUE THREAD

**Issue by aptalca** [kgretzky/pwndrop#12]
If I define a custom location for `admin` in the ini, a location other than next to the binary, the server starts, but there are no admin files generated in the custom location and thus no access to web gui.

One question I have is, does the admin folder contain and files or folders that need to be persistent?

The reason I'm asking is because in a docker setting, the container is ephemeral. So any data that needs to persist, we save to a folder that is mapped (or symlink). If there are no files in admin that need to persists, I won't worry about it.

Thanks

EDIT: Since opening this issue, we switched to multi-arch images and are now compiling from source. I see that the makefile copies the admin folder contents, so we followed suit. We'll keep the admin folder inside the container and it will be updated along with the binary.

That would be great if you can confirm that the admin folder contents are all ephemeral. Thanks

**Comment by kgretzky** [comment]
Yes, admin folder contents are all ephemeral as it just contains all the web content for the admin panel.

All the user data, including the local database, uploaded files and TLS certificates are stored in the `./data` folder. Default: `/usr/local/pwndrop/data`.

**Comment by aptalca** [comment]
Great, thanks
