### ISSUE TITLE
Can't set up a reverse proxy?

### ISSUE THREAD

**Issue by FuzzyMistborn** [kgretzky/pwndrop#17]
I have been trying to get this to work behind a reverse proxy without much success.  Is this not currently supported?

**Comment by FuzzyMistborn** [comment]
Nevermind, working now (not sure what I did)

**Comment by Wh1t3Rose** [comment]
Fuck You. What did you do to fix this.

**Comment by FuzzyMistborn** [comment]
With that language I'm certainly not about to help you.

**Comment by Wh1t3Rose** [comment]
Whatever dude. Your a dick anyways. Hurrdurr I know the answer but I ain't gonna post it cause I got cum for brains HURRDURR.

FUCK YOU.

**Comment by FuzzyMistborn** [comment]
If you read my second post I stated "not sure what I did" so clearly I don't know the answer.  Bye.

**Comment by visualblind** [comment]
I know this is closed but just wanted to add my two cents. If this thread was referring to the docker version of pwndrop then you'll **need a common docker network** between the pwndrop and reverse proxy containers.
If you used docker-compose and included both of the containers within the same yaml file, then this step is not necessary as compose automatically links the containers together via a common docker network. However this looks unlikely as the official documentation seems to have left out the docker-compose folks.

`Usage:  docker network connect [OPTIONS] NETWORK CONTAINER`

Here is my output of `docker network inspect pwndrop_default` which shows my nginx and pwndrop containers:

```
[
    {
        "Name": "pwndrop_default",
        "Id": "8df26ce8ed3e4bd073b97d930ef4ad44a323416a5a73fc086016840615bf777f",
        "Created": "2021-06-15T04:08:08.322263246-07:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "9baddab33c7ae492e8fc42142bb01c38f3e5aec52304d7a4d7862d1feed8b1bb": {
                "Name": "nginx",
                "EndpointID": "984018303eff68b5d4f44a31557d5961714284238619e7ec2b638f2f374b5ab2",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
            "ace7eed2fb14f0cbd9f28ef1654c9e9af1980da1e63d70b20fc4092e1d46f443": {
                "Name": "pwndrop",
                "EndpointID": "a09ff87a2762586971a1b37e30e140b7ee2675baef8b112e2980328aee38e498",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "pwndrop",
            "com.docker.compose.version": "1.25.4"
        }
    }
]
```

**Comment by Nukem51** [comment]
Hello all i am also having issues with a nginx reverse proxy setup @FuzzyMistborn would you be willing to share your nginx config please?

**Comment by FuzzyMistborn** [comment]
Sorry I no longer use nginx.
