### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by bielej** [kgretzky/pwndrop#4]
Hello,
Will there be a Docker image available?

**Comment by kgretzky** [comment]
Yes. I'm waiting for a pull request.

**Comment by alexanderadam** [comment]
But could you let this open then please?
I mean, this issue isn't solved yet, right? :thinking:

**Comment by HarshaVardhanJ** [comment]
Hey! I've created a [Docker image](https://hub.docker.com/r/harshavardhanj/pwndrop). I've tested it and have not found any issues so far. Would you like me to submit a PR?
